# Generated by Django 6.0.7 on 2026-07-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('organisation_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('custom_days', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('input_type', models.CharField(choices=[('pdf', 'PDF File'), ('url', 'Web URL'), ('text', 'Manual Text'), ('icp', 'Existing ICP')], default='text', max_length=20)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('from_document_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('roadblocks', models.TextField(blank=True, null=True)),
                ('pain_points', models.TextField(blank=True, null=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_rel', to='pulses.pulse')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords_rel', to='pulses.pulse')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=150, null=True)),
                ('company_size', models.CharField(blank=True, max_length=100, null=True)),
                ('revenue_range', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_count', models.CharField(blank=True, max_length=100, null=True)),
                ('target_account_focus', models.TextField(blank=True, null=True)),
                ('ideal_champion', models.TextField(blank=True, null=True)),
                ('tech_stack', models.TextField(blank=True, null=True)),
                ('ai_confidence_score', models.IntegerField(default=90)),
                ('ai_confidence_reason', models.TextField(blank=True, null=True)),
                ('pulse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='pulses.pulse')),
            ],
        ),
        migrations.CreateModel(
            name='BuyingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_signals_rel', to='pulses.pulse')),
            ],
        ),
        migrations.CreateModel(
            name='TargetCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=255)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='pulses.pulse')),
            ],
        ),
    ]
