# Generated by Django 6.0.7 on 2026-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='historical_lookback',
            field=models.CharField(choices=[('30d', 'Last 1 Month (30 Days)'), ('60d', 'Last 2 Months (60 Days)'), ('90d', 'Last 3 Months (90 Days)'), ('180d', 'Last 6 Months (180 Days)'), ('365d', 'Last 1 Year (365 Days)')], default='60d', max_length=10),
        ),
    ]
