# Generated by Django 6.0.7 on 2026-09-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0002_pulse_historical_lookback'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='target_geography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
