# Generated by Django 6.0.7 on 2026-09-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0003_pulse_target_geography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulse',
            name='custom_days',
        ),
        migrations.AlterField(
            model_name='pulse',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
    ]
