# Generated by Django 6.0.7 on 2026-07-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('publication_date', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_reason', models.TextField(blank=True, null=True)),
                ('delta_summary', models.TextField(blank=True, null=True)),
                ('is_relevant', models.BooleanField(default=False)),
                ('relevance_score', models.IntegerField(default=0)),
                ('buying_signal', models.CharField(blank=True, max_length=255, null=True)),
                ('relevance_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('relevance_reason', models.TextField(blank=True, null=True)),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('is_summarized', models.BooleanField(default=False)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('matched_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='discovery.article')),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_articles', to='pulses.pulse')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_tier', models.CharField(max_length=50)),
                ('corrected_tier', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='discovery.article')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('articles_scraped', models.IntegerField(default=0)),
                ('articles_relevant', models.IntegerField(default=0)),
                ('leads_extracted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='pulses.pulse')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('buying_signal', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_competitors', to='pulses.pulse')),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_competitors', to='discovery.article')),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_competitors', to='discovery.discoveryrun')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('buying_signal', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_companies', to='pulses.pulse')),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_companies', to='discovery.article')),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_companies', to='discovery.discoveryrun')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='discovery_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_articles', to='discovery.discoveryrun'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
                ('buying_signal', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_leads', to='discovery.discoveryrun')),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_leads', to='pulses.pulse')),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_leads', to='discovery.article')),
            ],
        ),
    ]
