# Generated by Django 6.0.7 on 2026-09-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryrun',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discoveryrun',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discoveryrun',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
