# Generated by Django 6.1.1 on 2026-09-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_discoveryrun_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='running', max_length=20),
        ),
    ]
