# Generated by Django 6.1.1 on 2026-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_alter_discoveryrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
