# Generated by Django 6.1.1 on 2026-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_lead_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='competitor_type',
            field=models.CharField(blank=True, choices=[('direct', 'Direct Competitor'), ('indirect', 'Indirect Alternative')], default='direct', max_length=50, null=True),
        ),
    ]
